name: UhcStats
main: com.gmail.mezymc.stats.UhcStats
version: ${project.version}
description: Adds a stat system to UhcCore (https://www.spigotmc.org/resources/uhc-core-automated-uhc-for-minecraft-1-8-1-14.47572/)
author: Mezy
soft-depend: [PlaceholderAPI]
depend: [UhcCore]
api-version: 1.13
commands:
  stats:
    description: "This command is used to show your stats in UHC."
    usage: "/stats or /uhcstats"
    aliases: [ uhcstats ]